Stock repear has issues with 'unicode' filenames on Windows - that is to say, filenames which cannot be represented properly in an ASCII encoding. Ironically, there is no need for that incompatibility for as far I can make out, although my knowledge of the handling of such files on Linux and compatriots is rather minimal. The errors one gets while freezing using stock repear look like the following:
ERROR: directory entry `01 - ????????.mp3' is inaccessible

This commit puts things into a workable shape on Windows, although I have not tested them for Linux compatibility. I put in a lot more changes than minimally necessary to get it working for myself, but I wanted to avoid things blowing up due to laziness on my part. :)

NOTE 1:

There are still some things left that are likely to break:

* Dissecting the music library.

* Transcoding from .ogg to .mp3 while freezing.

NOTE 2:

Make sure to unfreeze your library and to 'repear.py reset' before using this patch. The repear cache now carries unicode filenames where it previously did not, which might be cause for incompatibilities were one to mix and match.

NOTE 3:

Use at your own risk. I am not in the slightest responsible for anything other than good and positive results.